### PR TITLE
Fix #12: Handle existing builds

### LINKED ISSUE #12: Update intermine_builder to handle an already built mine
This would require a PR to https://github.com/intermine/docker-intermine-gradle, and probably this repository as well.

intermine_builder is a docker container you can find in the folder of the same name, in the repository linked above. Right now it will build an InterMine instance from scratch every time, but we want it to handle a previously built mine on which it will only run `./gradlew cargoDeployRemote` to deploy to the tomcat docker container.

The already built mine will be present in `$XDG_DATA_HOME/intermine_boot/docker/data/mine/biotestmine` (on Linux this is `~/.local/share/intermine_boot`). Currently, intermine_boot will delete the *docker* folder if it already exists, to start from scratch, so this behaviour will have to be changed to handle this new usecase.

In the future, we will also want to support building a mine saved as an archive, but that isn't a requirement for this issue.

You can start working on this issue immediately without waiting to be assigned (but please add a comment), even if someone has commented before you. We've decided to not assign issues and allow anyone interested to submit a PR. Obviously we won't be able to merge all the PRs, so don't worry about being first. All PRs whether merged or not, will be part of our evaluation of an intern.

It would also be great if you could explain your approach and rationale in the PR description. This only needs to be as long or as in depth as you feel it needs to be for the specific task.

### PR DESCRIPTION
**Pull request by 22PoojaGaur**
PR for #12 
Updated the code to create a config file from command line options
and to not delete already built mine if configs are same.

### CODE REVIEW

**Comment by 22PoojaGaur** [comment]
I have added check for branch and repo.

I was a bit confused whether to use `im_version` for checking commit version or handle it separately.

**Comment by heralden** [comment]
I'm very sorry I forgot about this PR! Now I remember what we meant by "config file". :smile: 

This seems like it can work with some small adjustments. I get `NameError: name 'pkl' is not defined` when testing it, so I guess you need to import pkl?

When `_is_conf_same` is true, it will exit the function with `return`. We still want docker-compose to bring up the containers though, so you should remove this. Just make sure you nest the `Repo.clone_from` into the else statement under `shutil.rmtree`, to avoid it failing when the directory already exists.

Regarding `im_version`, that does seem complicated so let's leave it for later!

**Comment by 22PoojaGaur** [comment]
@uosl I have handled the comments, please take a look.

**Review by heralden — APPROVED** [review]
Thanks, this did the trick!

It will complain about the missing boto3 dependency added in a different PR, but I will fix this after merging.

**Pull request merged**
